<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>SIGN UP</h1>
<form action="/signUp" method="post">
    <div>
        <input type="email" name="email" placeholder="EMAIL">
    </div>
    <div>
        <input type="password" name="password" placeholder="PASSWORD">
    </div>
    <div>
        <input type="text" name="name" placeholder="NAME">
    </div>
    <div>
        <input type="text" name="nick" placeholder="NICK">
    </div>
    <div>
        <input type="submit" value="SIGN UP">
    </div>
</form>
</body>
</html>